# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

    #- run: npm test

name: Node Package

on:
  push:
    branches: ['main']

jobs:
  quality:
    run-ons: ${{ matrix.os }}

    strategy:
      matrix:
        node-versions: ['16.16.0', '16']
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-versions }}
      uses: actions/setup-node@v3
      with:
        node-versions: ${{ matrix.node-version }}
    - run: npm ci