name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.16.0
      uses: actions/setup-node@v1
      with:
        node-version: 16.16.0
    - run: npm ci
    # - run: npm run lint
    - run: npm test
  # package:
  #   needs: [build]
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js 14.x
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 14.x
  


# jobs:
#   quality:
#     runs-on: ${{ matrix.os }}

#     strategy:
#       matrix:
#         node-versions: ['16.16.0', '16']
#         os: [ ubuntu-latest ]

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-versions }}
#       uses: actions/setup-node@v3
#       with:
#         node-versions: ${{ matrix.node-version }}
#     - run: npm ci