name: Release

on:
  push:
    branches: [main, staging]

jobs:
  quality:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest]

    steps:

    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node-version}}
        registry-url: https://npm.pkg.github.com/
        scope: "@captmoar-toctoc"
    - name: Install semantic release
      run: npm install --save-dev @semantic-release/changelog @semantic-release/git @semantic-release/github
    - name: Dependency installs
      run: npm ci
    - name: Testing
      run: npm run test
    - name: rollup compiler
      run: npm run rollup
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
