name: Release

on:
  push:
    branches: [main, beta]

jobs:
  quality:
    runs-on: ${{matrix.os}}

    strategy:
      node-version: [16, 18]
      os: [ubuntu-latest]

    steps:

    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
    - name: Dependency installs
      run: npm ci
    - name: Testing
      run: npm run test
    - name: rollup compiler
      run: npm run rollup
      
      
# env:
#   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# jobs:
#   release:
#     name: Release
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#     - name: Setup Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: 16.16.0
#     - name: Install dependencies
#       run: npm ci
#     - run: echo "registry=https://npm.pkg.github.com/@captmoar-toctoc" >> .npmrc  
#     - name: Install semantic-release extra plugins
#       run: npm install --save-dev @semantic-release/changelog @semantic-release/git @semantic-release/github
#     # - name: Lint
#     #   run: npm run lint-fix
#     - name: Test
#       run: npm run test:unit --if-present
#     - name: Build
#       run: npm rollup  
#     - name: Release
#       run: npx semantic-release